name: Dispatch Event
on:
  repository_dispatch:
    types: [build]
jobs:
  read-client-payload:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo ${{ github.event.client_payload.env }}
