name: Hello-World
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello World"
  get-versions:
    runs-on: ubuntu-latest
    steps:
      - name: multiline script
        run: |
          node -v
          npm -v
          ansible --version
          packer --version
          dotnet --info
          nginx -V
  exec-python-command:
    runs-on: ubuntu-latest
    steps:
      - name: execute Python command
        run: |
          import platform
          print(platform.processor())
        shell: python
